package views;

/**
 *
 * @author  : Purwa | Andrian M.D
 * Created  : 16 Apr 2026
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import config.KoneksiDatabase;

import java.util.ArrayList;

public class FormNilai extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormNilai
     */
    String idNilaiTerpilih = "";

    DefaultTableModel modelNilai;

    public FormNilai() {
        initComponents();

//        tampilData();
        loadNim();
//        loadMatkul();

        siapkanTabel();
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Nilai");
        model.addColumn("NIM");
        model.addColumn("Kode MK");
        model.addColumn("Semester");
        model.addColumn("Huruf");
        model.addColumn("Angka");

        tabelNilai.setModel(model);

        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM nilai");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_nilai"),
                    rs.getString("nim"),
                    rs.getString("kode_mk"),
                    rs.getString("semester_diambil"),
                    rs.getString("nilai_huruf"),
                    rs.getString("nilai_angka")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Load Data Nilai: " + e.getMessage());
        }
    }

    private void loadNim() {
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nim FROM mahasiswa");
            cb_nim.removeAllItems();
            cb_nim.addItem("-- Pilih NIM --");
            while (rs.next()) {
                cb_nim.addItem(rs.getString("nim"));
            }
        } catch (Exception e) {
        }
    }

    private void loadMatkul() {
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT kode_mk, nama_mk FROM mata_kuliah");
            cb_matkul.removeAllItems();
            cb_matkul.addItem("-- Pilih Mata Kuliah --");
            while (rs.next()) {
                cb_matkul.addItem(rs.getString("kode_mk") + " - " + rs.getString("nama_mk"));
            }
        } catch (Exception e) {
        }
    }

    private void siapkanTabel() {
        modelNilai = new DefaultTableModel();
        modelNilai.addColumn("ID Nilai");
        modelNilai.addColumn("Kode MK");
        modelNilai.addColumn("Semester");
        modelNilai.addColumn("Huruf");
        modelNilai.addColumn("Angka");
        modelNilai.addColumn("Status"); 
        tabelNilai.setModel(modelNilai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cb_nim = new javax.swing.JComboBox<>();
        tf_nama = new javax.swing.JTextField();
        tf_semester = new javax.swing.JTextField();
        cb_matkul = new javax.swing.JComboBox<>();
        cb_nilaiHuruf = new javax.swing.JComboBox<>();
        tf_nilai = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNilai = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Nilai");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        cb_nim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_nim.addActionListener(this::cb_nimActionPerformed);

        tf_nama.setEditable(false);
        tf_nama.setText("nama");

        tf_semester.setEditable(false);
        tf_semester.setText("semester");

        cb_matkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_matkul.addActionListener(this::cb_matkulActionPerformed);

        cb_nilaiHuruf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Nilai ---", "A", "B", "C", "D", "E" }));
        cb_nilaiHuruf.addActionListener(this::cb_nilaiHurufActionPerformed);

        tf_nilai.setEditable(false);
        tf_nilai.setText("Nilai");

        btn_edit.setText("edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_simpan.setText("simpan");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_clear.setText("Bersihkan");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        btn_hapus.setText("hapus");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        tabelNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNilai);

        btn_tambah.setText("tambah");
        btn_tambah.addActionListener(this::btn_tambahActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_nama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_nim, javax.swing.GroupLayout.Alignment.LEADING, 0, 216, Short.MAX_VALUE)
                            .addComponent(tf_semester, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_matkul, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_nilaiHuruf, javax.swing.GroupLayout.Alignment.LEADING, 0, 217, Short.MAX_VALUE)
                            .addComponent(tf_nilai, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_nilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tambah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nimActionPerformed
        // TODO add your handling code here:

        if (cb_nim.getSelectedIndex() > 0) {
            try {
                Connection conn = KoneksiDatabase.dB_koneksi();
                String nimDipilih = cb_nim.getSelectedItem().toString();

              
                String sqlMhs = "SELECT nama, semester_aktif FROM mahasiswa WHERE nim = ?";
                PreparedStatement pstMhs = conn.prepareStatement(sqlMhs);
                pstMhs.setString(1, nimDipilih);
                ResultSet rsMhs = pstMhs.executeQuery();
                if (rsMhs.next()) {
                    tf_nama.setText(rsMhs.getString("nama"));
                    tf_semester.setText(rsMhs.getString("semester_aktif"));
                }
                rsMhs.close();
                pstMhs.close();

                modelNilai.setRowCount(0);
                String sqlNilai = "SELECT * FROM nilai WHERE nim = ?";
                PreparedStatement pstNilai = conn.prepareStatement(sqlNilai);
                pstNilai.setString(1, nimDipilih);
                ResultSet rsNilai = pstNilai.executeQuery();
                while (rsNilai.next()) {
                    modelNilai.addRow(new Object[]{
                        rsNilai.getString("id_nilai"),
                        rsNilai.getString("kode_mk"),
                        rsNilai.getString("semester_diambil"),
                        rsNilai.getString("nilai_huruf"),
                        rsNilai.getString("nilai_angka"),
                        "Tersimpan"
                    });
                }
                rsNilai.close();
                pstNilai.close();

   
                String sqlMatkul = "SELECT k.kode_mk, m.nama_mk FROM krs k JOIN mata_kuliah m ON k.kode_mk = m.kode_mk "
                        + "WHERE k.nim = ? AND k.kode_mk NOT IN (SELECT kode_mk FROM nilai WHERE nim = ?)";
                PreparedStatement pstMatkul = conn.prepareStatement(sqlMatkul);
                pstMatkul.setString(1, nimDipilih);
                pstMatkul.setString(2, nimDipilih); 
                ResultSet rsMatkul = pstMatkul.executeQuery();

                cb_matkul.removeAllItems();
                cb_matkul.addItem("-- Pilih Matkul Kontrak --");
                while (rsMatkul.next()) {
                    cb_matkul.addItem(rsMatkul.getString("kode_mk") + " - " + rsMatkul.getString("nama_mk"));
                }
                rsMatkul.close();
                pstMatkul.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error load data: " + e.getMessage());
            }
        } else {
            tf_nama.setText("");
            tf_semester.setText("");
            cb_matkul.removeAllItems();
            if (modelNilai != null) {
                modelNilai.setRowCount(0);
            }
        }
    }//GEN-LAST:event_cb_nimActionPerformed

    private void cb_matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_matkulActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cb_matkulActionPerformed

    private void cb_nilaiHurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nilaiHurufActionPerformed
        // TODO add your handling code here:
        int indexDipilih = cb_nilaiHuruf.getSelectedIndex();

        if (indexDipilih > 0) {
            String huruf = cb_nilaiHuruf.getSelectedItem().toString();
            switch (huruf) {
                case "A":
                    tf_nilai.setText("4");
                    break;
                case "B":
                    tf_nilai.setText("3");
                    break;
                case "C":
                    tf_nilai.setText("2");
                    break;
                case "D":
                    tf_nilai.setText("1");
                    break;
                case "E":
                    tf_nilai.setText("0");
                    break;
                default:
                    tf_nilai.setText("");
                    break;
            }
        } else {
            tf_nilai.setText("");
        }
    }//GEN-LAST:event_cb_nilaiHurufActionPerformed

    private void tabelNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNilaiMouseClicked
        // TODO add your handling code here:

        int baris = tabelNilai.getSelectedRow();
        if (baris != -1) {

            idNilaiTerpilih = tabelNilai.getValueAt(baris, 0).toString(); 
            String huruf = tabelNilai.getValueAt(baris, 3).toString(); 
            String matkul = tabelNilai.getValueAt(baris, 1).toString();

            cb_nilaiHuruf.setSelectedItem(huruf);
            cb_matkul.setSelectedItem(matkul);

        }

    }//GEN-LAST:event_tabelNilaiMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:

        if (modelNilai.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tabel masih kosong!");
            return;
        }

        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            String sql = "INSERT INTO nilai (nim, kode_mk, semester_diambil, nilai_huruf, nilai_angka) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            String nim = cb_nim.getSelectedItem().toString();
            int jumlahDraft = 0;

  
            for (int i = 0; i < modelNilai.getRowCount(); i++) {
                String status = modelNilai.getValueAt(i, 5).toString();

             
                if (status.equals("Draft")) {
                    pst.setString(1, nim);
                    pst.setString(2, modelNilai.getValueAt(i, 1).toString());
                    pst.setString(3, modelNilai.getValueAt(i, 2).toString()); 
                    pst.setString(4, modelNilai.getValueAt(i, 3).toString()); 
                    pst.setString(5, modelNilai.getValueAt(i, 4).toString()); 
                    pst.addBatch();

                    modelNilai.setValueAt("Tersimpan", i, 5);
                    jumlahDraft++;
                }
            }

            if (jumlahDraft > 0) {
                pst.executeBatch(); 
                JOptionPane.showMessageDialog(this, jumlahDraft + " nilai berhasil disimpan ke Database!");

                cb_nimActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada nilai baru (Draft) yang perlu disimpan.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan ke DB: " + e.getMessage());
        }


    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, "Dalam mode Keranjang/Draft, jika terdapat kesalahan silakan HAPUS matkul dari tabel, lalu TAMBAH kembali dengan nilai yang benar.");
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:

        int baris = tabelNilai.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang mau dihapus di tabel!");
            return;
        }

        String status = modelNilai.getValueAt(baris, 5).toString();
        String idNilai = modelNilai.getValueAt(baris, 0).toString();

        if (status.equals("Draft")) {
            modelNilai.removeRow(baris);
            cb_nimActionPerformed(null);
        } else {
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus nilai ini dari database?", "Hapus", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    Connection conn = KoneksiDatabase.dB_koneksi();
                    PreparedStatement pst = conn.prepareStatement("DELETE FROM nilai WHERE id_nilai=?");
                    pst.setString(1, idNilai);
                    pst.execute();

                    JOptionPane.showMessageDialog(this, "Nilai terhapus dari Database!");
                    cb_nimActionPerformed(null); 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        idNilaiTerpilih = ""; 
        cb_nim.setSelectedIndex(0); 
        cb_nilaiHuruf.setSelectedIndex(0);
        tf_nilai.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        if (cb_nim.getSelectedIndex() <= 0 || cb_matkul.getSelectedIndex() <= 0 || cb_nilaiHuruf.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Pilih Matkul dan Nilai Huruf!");
            return;
        }

        String kodeMk = cb_matkul.getSelectedItem().toString().split(" - ")[0].trim();
        String semester = tf_semester.getText();
        String huruf = cb_nilaiHuruf.getSelectedItem().toString().trim();
        String angka = tf_nilai.getText();

        modelNilai.addRow(new Object[]{"-", kodeMk, semester, huruf, angka, "Draft"});

        cb_matkul.removeItemAt(cb_matkul.getSelectedIndex());

        cb_nilaiHuruf.setSelectedIndex(0);
        tf_nilai.setText("");
    }//GEN-LAST:event_btn_tambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_matkul;
    private javax.swing.JComboBox<String> cb_nilaiHuruf;
    private javax.swing.JComboBox<String> cb_nim;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelNilai;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nilai;
    private javax.swing.JTextField tf_semester;
    // End of variables declaration//GEN-END:variables
}
