/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import config.KoneksiDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author  : Purwa | Andrian M.D
 * Created  : 16 Apr 2026
 */

public class FormAddUsers extends javax.swing.JInternalFrame {

    String idUserTerpilih = "";

    /**
     * Creates new form FormAkun
     */
    public FormAddUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tf_namaLengkap = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();
        cbb_role = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        btn_bersihkan = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Users");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        tf_namaLengkap.setText("Nama lengkap");

        tf_username.setText("Username");

        pf_pass.setText("jPasswordField1");

        cbb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Role ---", "operator" }));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_bersihkan.setText("bersihkan");
        btn_bersihkan.addActionListener(this::btn_bersihkanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_namaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_bersihkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(cbb_role, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pf_pass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(tf_namaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String namaLengkap = tf_namaLengkap.getText();
        String username = tf_username.getText();
        String password = String.valueOf(pf_pass.getPassword());

        if (namaLengkap.isEmpty() || username.isEmpty() || password.isEmpty() || cbb_role.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data (Nama, Username, Password, dan Role)!");
            return; // Hentikan proses jika ada yang kosong
        }

        try {
            // 2. Query Insert ke Database
            Connection conn = KoneksiDatabase.dB_koneksi();
            String sql = "INSERT INTO user (nama_lengkap, username, password, role) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, namaLengkap);
            pst.setString(2, username);
            pst.setString(3, password);
            pst.setString(4, cbb_role.getSelectedItem().toString());

            // 3. Eksekusi
            pst.execute();
            JOptionPane.showMessageDialog(this, "Sukses! User baru berhasil ditambahkan.");

            // 4. Bersihkan form setelah berhasil disimpan
            btn_bersihkanActionPerformed(evt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan user: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihkanActionPerformed
        // TODO add your handling code here:
        tf_namaLengkap.setText("");
        tf_username.setText("");
        pf_pass.setText(""); // Mengosongkan field password
        cbb_role.setSelectedIndex(0); // Kembalikan ke pilihan default (misal: "-- Pilih Role --")

        tf_namaLengkap.requestFocus();
    }//GEN-LAST:event_btn_bersihkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersihkan;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cbb_role;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JTextField tf_namaLengkap;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
