/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import config.KoneksiDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author  : Purwa | Andrian M.D
 * Created  : 16 Apr 2026
 */

public class FormChangePass extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormChangePass
     */
    public FormChangePass() {
        initComponents();
        loadUsernames();
    }

    private void loadUsernames() {
        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT username FROM user");

            cbb_username.removeAllItems();
            cbb_username.addItem("-- Pilih Username --");

            while (rs.next()) {
                cbb_username.addItem(rs.getString("username"));
            }

            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat daftar user: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pf_passBaru = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pf_konfirmasi = new javax.swing.JPasswordField();
        btn_simpan = new javax.swing.JButton();
        btn_bersihkan = new javax.swing.JButton();
        cbb_username = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Change Password");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password Baru");

        pf_passBaru.setText("jPasswordField1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Konfirmasi Password");

        pf_konfirmasi.setText("jPasswordField1");

        btn_simpan.setText("simpan");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_bersihkan.setText("bersihkan");
        btn_bersihkan.addActionListener(this::btn_bersihkanActionPerformed);

        cbb_username.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pf_konfirmasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addComponent(btn_bersihkan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbb_username, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pf_passBaru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cbb_username, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_passBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:

        if (cbb_username.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Harap pilih username terlebih dahulu!");
            return;
        }

        String username = cbb_username.getSelectedItem().toString();
        String passBaru = String.valueOf(pf_passBaru.getPassword());
        String konfirmasi = String.valueOf(pf_konfirmasi.getPassword());

        if (passBaru.isEmpty() || konfirmasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi Password Baru dan Konfirmasi!");
            return;
        }

        if (!passBaru.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(this, "Password Baru dan Konfirmasi tidak cocok!");
            pf_passBaru.setText("");
            pf_konfirmasi.setText("");
            pf_passBaru.requestFocus();
            return;
        }

        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            
            String sqlUpdate = "UPDATE user SET password = ? WHERE username = ?";
            PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
            pstUpdate.setString(1, passBaru);
            pstUpdate.setString(2, username);

            int berhasil = pstUpdate.executeUpdate();

            if (berhasil > 0) {
                JOptionPane.showMessageDialog(this, "Password untuk user '" + username + "' berhasil diperbarui!");
                btn_bersihkanActionPerformed(evt); 
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal meriset password: " + e.getMessage());
        }

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihkanActionPerformed
        // TODO add your handling code here:
        cbb_username.setSelectedIndex(0);
        pf_passBaru.setText("");
        pf_konfirmasi.setText("");
        cbb_username.requestFocus();
    }//GEN-LAST:event_btn_bersihkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersihkan;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cbb_username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pf_konfirmasi;
    private javax.swing.JPasswordField pf_passBaru;
    // End of variables declaration//GEN-END:variables
}
