/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import config.KoneksiDatabase;
import javax.swing.JOptionPane;

public class FormDosen extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDosen
     */
    public FormDosen() {
        initComponents();

        tampilData();
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIP");
        model.addColumn("Nama Dosen");
        model.addColumn("Jabatan");

        table_dosen.setModel(model);

        try {
            Connection conn = KoneksiDatabase.dB_koneksi();
            Statement st = conn.createStatement();
            // Sesuaikan nama tabel 'dosen' jika di databasemu berbeda
            ResultSet rs = st.executeQuery("SELECT * FROM dosen");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nip"),
                    rs.getString("nama"),
                    rs.getString("jabatan")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data Dosen: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tf_nip = new javax.swing.JTextField();
        tf_dosen = new javax.swing.JTextField();
        cbb_jabatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dosen = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Form Dosen");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        tf_nip.setText("NIP");

        tf_dosen.setText("dosen");

        cbb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dosen pengajar", "Kaprodi", "Dospem" }));

        table_dosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_dosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_dosen);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Daftar Dosen");

        btn_edit.setText("edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_tambah.setText("tambah");
        btn_tambah.addActionListener(this::btn_tambahActionPerformed);

        btn_hapus.setText("hapus");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        btn_bersih.setText("bersihkan");
        btn_bersih.addActionListener(this::btn_bersihActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dosen, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_dosen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_dosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dosenMouseClicked
        // TODO add your handling code here:

        int baris = table_dosen.getSelectedRow();
        if (baris != -1) {
            tf_nip.setText(table_dosen.getValueAt(baris, 0).toString());
            tf_dosen.setText(table_dosen.getValueAt(baris, 1).toString());
            cbb_jabatan.setSelectedItem(table_dosen.getValueAt(baris, 2).toString());

            tf_nip.setEditable(false);
        }
    }//GEN-LAST:event_table_dosenMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "INSERT INTO dosen (nip, nama, jabatan) VALUES (?, ?, ?)";
            Connection conn = KoneksiDatabase.dB_koneksi();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tf_nip.getText());
            pst.setString(2, tf_dosen.getText());
            pst.setString(3, cbb_jabatan.getSelectedItem().toString());

            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Disimpan!");

            tampilData(); // Refresh tabel
            btn_bersihActionPerformed(evt); // Bersihkan form

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "UPDATE dosen SET nama=?, jabatan=? WHERE nip=?";
            Connection conn = KoneksiDatabase.dB_koneksi();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, tf_dosen.getText());
            pst.setString(2, cbb_jabatan.getSelectedItem().toString());
            pst.setString(3, tf_nip.getText()); // NIP sebagai kunci pencarian

            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Diubah!");

            tampilData();
            btn_bersihActionPerformed(evt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Mengubah Data: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus dosen ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM dosen WHERE nip=?";
                Connection conn = KoneksiDatabase.dB_koneksi();
                PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, tf_nip.getText());

                pst.execute();
                JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Dihapus!");

                tampilData();
                btn_bersihActionPerformed(evt);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus Data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        // TODO add your handling code here:

        tf_nip.setText("");
        tf_dosen.setText("");
        cbb_jabatan.setSelectedIndex(0); // Kembali ke pilihan pertama

        // Buka kembali form NIP untuk input data baru
        tf_nip.setEditable(true);
        tf_nip.requestFocus();
    }//GEN-LAST:event_btn_bersihActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cbb_jabatan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_dosen;
    private javax.swing.JTextField tf_dosen;
    private javax.swing.JTextField tf_nip;
    // End of variables declaration//GEN-END:variables
}
